# Generated by Django 3.1.4 on 2020-12-07 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(help_text='用户名', max_length=10, unique=True, verbose_name='用户名')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
